(function () {
      app.constant('menus', [
      	{ 
      		title : "Job Feed", 
      		link: '#/',
      		target : "",
      		class: "fa fa-tachometer"
      	},
      	{ 
      		title : "Create Order",
      		link: '#/order/create/new',
      		target: "",
      		class: "fa fa-plus-square"
      	},
      	{ 
      		title : "Work Order",
      		link: '#/workorder',
      		target: "",
      		class: "fa fa-pencil-square-o"
      	},
      	{ 
      		title : "Bulk Order",
      		link: '#/bulkorder',
      		target: "",
      		class: "fa fa-list-alt"
      	},
      	{ 
      		title : "Bulk Assign",
      		link: '#/bulkassign',
      		target: "",
      		class: "fa fa-list-alt"
      	},
      	{ 
      		title : "Report", 
      		link: '#/report',
      		target : "",
      		class: "fa fa-file-text-o"
      	},
      	{ 
      		title : "Users", 
      		link: '#/users',
      		target: "",
      		class: "fa fa-user-plus"
      	},
      	{ 
      		title : "Tracking Map",
      		link: '#/tracking-map',
      		target: "",
      		class: "fa fa-crosshairs"
      	},
      	{ 
      		title : "Product Category",
      		link: '#/products-category',
      		target: "",
      		class: "fa fa-tags"
      	},
      	{ 
      		title : "Stores", 
      		link: '#/stores',
      		target: "",
      		class: "fa fa-map-signs"
      	},
      	{ 
      		title : "Job Activity", 
      		link: '#/jobactivity',
      		target: "",
      		class: "fa fa-tasks"
      	},
      ]);

      app.constant('tracking_host', "http://gofetch.cloudapp.net:1337/");
      app.constant('signlr_link', "http://gofetch.cloudapp.net:1001/signalr/hubs");
      app.constant('jobNotification_link', "http://gofetch.cloudapp.net:1002/signalr/hubs")
      app.constant('reportServiceUrl', "http://gobdsif.cloudapp.net/");
      // app.constant('reportServiceUrl', "http://127.0.0.1:8000/");

      app.constant('templates', {
      	sidebar: 'app/views/sidebar.html',
      	availableAsset: 'app/views/detailsJob/availableAsset.html'
      });

      app.constant('COLOR', {
      	"red" : "#F44336",
      	"green" : "#4CAF50",
      	"yellow" : "#FFEB3B"
      });

      app.constant('Areas', [
                  "Outside Dhaka",
      		"Agargaon",
                  "AGB Colony",
                  "Ananda Nagar",
                  "Arambag Housing",
                  "Asad Gate",
                  "Askona",
                  "Avenue",
                  "Azimpur",
                  "Badda",
                  "Bagh Bari",
                  "Baily Road",
                  "Banani C/A",
                  "Banani DOHS",
                  "Banani R/A",
                  "Bangla College",
                  "Banglamotor",
                  "Bangshal",
                  "Baridhara DOHS",
                  "Baridhara",
                  "Bashabo",
                  "Bashundhara R/A",
                  "Baunia",
                  "BDR Gate",
                  "Bijay Sarani",
                  "Bijoynagar",
                  "Bishil",
                  "Bordita Pallabi",
                  "BUET",
                  "Camp Area",
                  "Cantonment",
                  "Chankharpul",
                  "ChawkBazar",
                  "Choto Dia Bari",
                  "Chowdhuripara",
                  "Darus Salam",
                  "Dhaka Housing",
                  "Dhaka Uddan",
                  "Dhaka Uni.",
                  "Dhanmondi R/A",
                  "Dilkusha",
                  "Doinik Bangla",
                  "Dokkhinkhan",
                  "Elephant Raod",
                  "Eskaton Road",
                  "Fakirapul",
                  "Farmgate",
                  "Faydabad",
                  "Gabtoli",
                  "Gandaria",
                  "Gaoail",
                  "Goran",
                  "Green Road",
                  "Gulistan",
                  "Gulshan - 2",
                  "Gulshan -1",
                  "Gulshan Avenue",
                  "Hajicamp",
                  "Hatirpul",
                  "Indira Road",
                  "Jaganathpur",
                  "Jatrabari",
                  "Jurain",
                  "Kafrul (Cant.)",
                  "Kafrul",
                  "Kakrail",
                  "Kalabagan",
                  "Kallyanpur Bus Stand",
                  "Kallyanpur",
                  "Kamal Attaturk",
                  "Kawran Bazar",
                  "Kazipara",
                  "Khathalbagan",
                  "Khilgaon",
                  "Khilkhet",
                  "Kuril",
                  "Lakecity/ Pinkcity",
                  "Lalbagh",
                  "Lalmatia",
                  "Malibagh",
                  "Manda",
                  "Manik Mia Avenue",
                  "Manikdi",
                  "Merul Badda",
                  "Mirbagh",
                  "Mirpur 1",
                  "Mirpur 10",
                  "Mirpur 11/11.5",
                  "Mirpur 12",
                  "Mirpur 14",
                  "Mirpur 2",
                  "Mirpur 6",
                  "Mirpur 7",
                  "Mirpur DOHS",
                  "Miurpur 13",
                  "Moddho Badda",
                  "Moghbazar",
                  "Mohakhali Bus",
                  "Mohakhali DOHS",
                  "Moham. Bus Stand",
                  "Mohammadpur Housing",
                  "Mohkhali C/A",
                  "Monipur",
                  "Monipuripara",
                  "Motijheel C/A",
                  "Multiplan Center",
                  "Nabisko",
                  "Nakhalpara",
                  "Narinda",
                  "Navy Head Quarter",
                  "Nayapaltan",
                  "Nayatola",
                  "Niketan",
                  "Nikunja 1",
                  "Nikunja 2",
                  "Nobodoy Housing",
                  "Nurjahan Road",
                  "Paik para",
                  "Pallabi",
                  "Panthapath",
                  "Pirerbagh",
                  "Postagola",
                  "Purana Paltan",
                  "R/K Mission Road",
                  "Raja Bazar",
                  "Rampura",
                  "Rayer Bazar",
                  "Ring Road",
                  "Rupnagar R/A",
                  "Sadarghat",
                  "Segunbagicha",
                  "Shahbag",
                  "Shantinagar",
                  "Shaymoli",
                  "Shewrapara",
                  "Staff Quarter",
                  "Stand.",
                  "Subhanbag",
                  "Sukrabad",
                  "Tajmohol Road",
                  "Taltala",
                  "Tatibazar",
                  "Tejgaon Industrial Area",
                  "Tejgaon Link Road",
                  "Tezturi para",
                  "Topkhana Road",
                  "Town Hall",
                  "Turag",
                  "Uttara Sector 1",
                  "Uttara Sector 10",
                  "Uttara Sector 11",
                  "Uttara Sector 12",
                  "Uttara Sector 13, 14",
                  "Uttara Sector 2",
                  "Uttara Sector 3",
                  "Uttara Sector 4",
                  "Uttara Sector 5",
                  "Uttara Sector 6",
                  "Uttara Sector 7",
                  "Uttara Sector 8",
                  "Uttara Sector 9",
                  "Uttarkhan",
                  "Vasantek",
                  "Vatara",
                  "Wari",
                  "Zigatala"
      ]);      
})();